#ifndef DEEPREINFORCEMENTLEARNING_cn4_PLAYERCOLOR_H
#define DEEPREINFORCEMENTLEARNING_cn4_PLAYERCOLOR_H

namespace cn4 {
	enum PlayerColor {
		NONE, YELLOW, RED
	};
}

#endif //DEEPREINFORCEMENTLEARNING_cn4_PLAYERCOLOR_H
